### PR TITLE
added rspec & factorgirl gems & first rspect test for index page

### PR DESCRIPTION
**Pull request by Edwin-F**
rspec_test1_success

### CODE REVIEW

**Comment by smiths15** [comment]
@Edwin-F looks good!

**Comment by smiths15** [comment]
Also, as part of the workflow process, request others to review the code under the "reviewers" section on the right-hand side of the screen. That way we're all notified of the when a new code needs review

**Review by JefeNelson — APPROVED** [review]
I was able to checkout locally and run the specs. 0 failures!

**Review by xelzi — COMMENTED** [review]
Ran with no errors!

**Review by xelzi — APPROVED** [review]

**Pull request merged**
