### PR TITLE
Installed Boostrap and Devise and simple log in to test

### PR DESCRIPTION
**Pull request by SomeRandom42**
I installed the gems Devise and Bootstrap, and made a simple log in at the top to test functionality. It worked. 
One thing is the email for local production may not work because I do not know your local port otherwise it is fine ! Let me know procedure for merging this into the main master and such I will not just merge by my self/

### CODE REVIEW

**Comment by smiths15** [comment]
@Edwin-F I checked locally and was able to sign up, sign out, and log in successfully

**Review by smiths15 — APPROVED** [review]
@Edwin-F I checked locally and was able to sign up, sign out, and log in successfully

**Comment by JefeNelson** [comment]
I was able to test it out also. It works for me just fine.

**Review by JefeNelson — APPROVED** [review]
I was able to test out also. It works just fine for me.

**Comment by xelzi** [comment]
Worked for me!

**Review by xelzi — APPROVED** [review]

**Pull request merged**
