### PR TITLE
Websocket actioncable

### PR DESCRIPTION
**Pull request by Edwin-F**
I got a websocket to work after some research, failures, and trial and error.  There no rspec tests for this at the moment. 
Before testing, check the config/environments/development.rb, and update the following:
config.action_cable.url = "ws://127.0.0.1:3030/cable" on line 57
to whatever port you use when you run your rails app. 
if you use local:3000, then update to "ws://http://localhost:3000/cable"

To test this, play a game on the web, with both players (example: one window is regular and the other in incognito window).
Make a move in one window, and the other players window should refresh as well with the updated piece position. 

Note, the response is slow, and sometimes doesn't refresh well. This might be due to javascript I used ( window.location.reload(true) ) in the 
app/assests/javascripts/channels/pieces.js line 8.
Later on when we figure out how to update the app without a page refresh using javascript, we can update the code here.

Any feedback is appreciated.

Thanks.
FYI, here is the reference I used to implement this websocket in case you wanted to learn this. This was a ruby on rails example with puma server. Other ones I seen used the sinatra framework with a thin server instead.
https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable

### CODE REVIEW

**Comment by xelzi** [comment]
@Edwin-F nice job with this. The only problem I see from testing is that the alert message saying that the other player has made a move shows up in both windows...however this makes sense given that I am logged in as the same player in both windows. 

So, nice work!

**Review by xelzi — APPROVED** [review]

**Comment by JefeNelson** [comment]
It's looking good Edwin. :)
I was wondering if you're able to check if there's an update issue with getting out of check. For me it doesn't update when a player is in check and gets out of it.

**Comment by Edwin-F** [comment]
Haven't had a chance to check that bug you mentioned Jeff. I will look at this tomorrow.

**Comment by Edwin-F** [comment]
I was not able to create this error.  Maybe draw how your pieces are on this 
https://lichess.org/editor
and I can position my pieces on this side to recreate this.  Thanks.

**Pull request merged**
